In [1]:
import numpy as np
A=np.arange(9)
B=A.reshape(3,3)
print(B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [2]:

for i in A:
	if(i%2==0):
		continue
	else:
		A[i]=-1
print(A)


[ 0 -1  2 -1  4 -1  6 -1  8]


In [3]:
x=np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y=np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])


print(np.where(x>y))
print(np.where(x==y))


(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


In [4]:
z= np.arange(100).reshape(5,-1)
print(z)
print(z[:,[0,1,2,3]])

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]
[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]


In [6]:

# arr= np.linspace(30,40,10, dtype=np.int32)
arr= np.random.randint(low=30, high=40, size=10)
print(arr)

[37 32 35 30 32 37 30 30 34 39]


In [7]:
A=np.array([(1,2,3),(4,5,6),(7,8,10)])
B=np.array([(7,8,10),(4,5,6),(1,2,3)])

In [8]:
C=A+B
print(C)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]


In [9]:
E=A-B
print(E)

[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [10]:
print(np.sum(A))

46


In [11]:
print(np.sum(B,axis=0))

[12 15 19]


In [12]:
print(np.sum(C,axis=1))

[31 30 31]


In [13]:
D=A.dot(B)
print(D)

[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]


In [14]:
C.sort()
print(C)

[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]


In [15]:
print(E.transpose())

[[-6  0  6]
 [-6  0  6]
 [-7  0  7]]
